runtime: python312
handlers:

# Initial route that will serve up index.html, main entry point to your app
- url: /
  secure: always
  static_files: build/index.html
  upload: build/.*

# Routing for typedoc, assets and favicon.ico to serve directly
- url: /((?:assets|docs)/.*|favicon\.ico)
  secure: always
  redirect_http_response_code: 301
  static_files: build/\1
  upload: build/.*
  
# Routing for any js files
- url: /(.*\.js)
  secure: always
  redirect_http_response_code: 301
  static_files: build/\1
  upload: build/.*\.js

# Routing for any css files
- url: /(.*\.css)
  secure: always
  redirect_http_response_code: 301
  static_files: build/\1
  mime_type: text/css
  upload: build/.*\.css
  
# Routing for anything (wild card) after
- url: /.*
  secure: always
  static_files: build/index.html
  upload: build/.*